[project]
name = 'simnet'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST3FFRX7C911PZP5RHE148YDVDD9JWVS6FZRA60VS.extension-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.send-many'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP000000000000000000002Q6VF78.pox-4'

[[project.requirements]]
contract_id = 'SP3D6PV2ACBPEKYJTCMH7HEN02KP87QSP8KTEH335.commission-trait'

[[project.requirements]]
contract_id = 'SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.ft-trait'

[[project.requirements]]
contract_id = 'SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.restricted-token-trait'

[[project.requirements]]
contract_id = 'SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SP16GEW6P7GBGZG0PXRXFJEMR3TJHJEY2HJKBP1P5.og-bitcoin-pizza-leather-edition'

[[project.requirements]]
contract_id = 'SP32AEEF6WW5Y0NMJ1S8SBSZDAY8R5J32NBZFPKKZ.micro-nthng'

[[project.requirements]]
contract_id = 'SP32AEEF6WW5Y0NMJ1S8SBSZDAY8R5J32NBZFPKKZ.nope'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

[[project.requirements]]
contract_id = 'SPDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTKAKKR5V.sip013-semi-fungible-token-trait'

[contracts.emergency-rules]
path = 'contracts/rules/emergency-rules.clar'
clarity_version = 4
epoch = "3.3"

[contracts.ext-sponsored-sbtc-transfer]
path = 'contracts/extensions/ext-sponsored-sbtc-transfer.clar'
clarity_version = 4
epoch = "3.3"

[contracts.ext-sponsored-sbtc-transfer-many]
path = 'contracts/extensions/ext-sponsored-sbtc-transfer-many.clar'
clarity_version = 4
epoch = "3.3"

[contracts.ext-sponsored-sbtc-transfer_test]
path = 'contracts/extensions/ext-sponsored-sbtc-transfer_test.clar'
clarity_version = 4
epoch = "3.3"

[contracts.ext-delegate-stx-pox-4]
path = 'contracts/extensions/ext-delegate-stx-pox-4.clar'
clarity_version = 4
epoch = "3.3"

[contracts.ext-delegate-stx-pox-4_flow_test]
path = 'contracts/extensions/ext-delegate-stx-pox-4_flow_test.clar'
clarity_version = 4
epoch = "3.3"

[contracts.ext-sponsored-transfer]
path = 'contracts/extensions/ext-sponsored-transfer.clar'
clarity_version = 4
epoch = "3.3"

[contracts.ext-sponsored-send-many]
path = 'contracts/extensions/ext-sponsored-send-many.clar'
clarity_version = 4
epoch = "3.3"

[contracts.ext-unsafe-sip010-transfer]
path = 'contracts/extensions/ext-unsafe-sip010-transfer.clar'
clarity_version = 4
epoch = "3.3"

[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 4
epoch = "3.3"

[contracts.inactive-observer]
path = 'contracts/admin/inactive-observer.clar'
clarity_version = 4
epoch = "3.3"

[contracts.no-rules]
path = 'contracts/rules/no-rules.clar'
clarity_version = 4
epoch = "3.3"

[contracts.rule-set-trait]
path = 'contracts/rule-set-trait.clar'
clarity_version = 4
epoch = "3.3"

[contracts.smart-wallet-with-rules]
path = 'contracts/smart-wallet-with-rules.clar'
clarity_version = 4
epoch = "3.3"

[contracts.smart-wallet-standard]
path = 'contracts/smart-wallet-standard.clar'
clarity_version = 4
epoch = "3.3"

[contracts.smart-wallet-standard-2]
path = 'contracts/smart-wallet-standard.clar'
clarity_version = 4
epoch = "3.3"


[contracts.smart-wallet-group]
path = 'contracts/smart-wallet-group.clar'
clarity_version = 4
epoch = "3.3"

[contracts.smart-wallet-group_test]
path = 'contracts/smart-wallet-group_test.clar'
clarity_version = 4
epoch = "3.3"

[contracts.smart-wallet-standard_test]
path = 'contracts/smart-wallet-standard_test.clar'
clarity_version = 4
epoch = "3.3"

[contracts.smart-wallet-endpoint]
path = 'contracts/smart-wallet-endpoint.clar'
clarity_version = 4
epoch = "3.3"


[contracts.smart-wallet-standard-auth-helpers]
path = 'contracts/smart-wallet-standard-auth-helpers.clar'
clarity_version = 4
epoch = "3.3"

[contracts.smart-wallet-trait]
path = 'contracts/smart-wallet-trait.clar'
clarity_version = 4
epoch = "3.3"

[contracts.smart-wallet-with-rules-trait]
path = 'contracts/smart-wallet-with-rules-trait.clar'
clarity_version = 4
epoch = "3.3"

[contracts.standard-rules]
path = 'contracts/rules/standard-rules.clar'
clarity_version = 4
epoch = "3.3"

[contracts.ext-test]
path = 'contracts/tests/ext-test.clar'
clarity_version = 4
epoch = "3.3"

[contracts.csw-registry]
path = 'contracts/csw-registry.clar'
clarity_version = 4
epoch = "3.3"

[contracts.csw-registry_test]
path = 'contracts/csw-registry_test.clar'
clarity_version = 4
epoch = "3.3"

# Dummy csw-trait implementations for csw-registry testing.

[contracts.dummy-csw]
path = 'contracts/tests/dummy-csw.clar'
clarity_version = 4
epoch = "3.3"


[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
